//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "ATB_Springbooot_WSSoapBinding", Namespace = "urn:ATB_Springbooot_WS")]
public partial class ATB_Springbooot_WSService : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private AuthenticationInfo authenticationInfoValueField;

    private System.Threading.SendOrPostCallback NotifyShipmentOrderConfirmationOperationCompleted;

    private System.Threading.SendOrPostCallback StatusUpdateOperationCompleted;

    /// <remarks/>
    public ATB_Springbooot_WSService()
    {
        //http://172.16.68.32:8080/arsys/services/ARService?server=172.16.68.32
        string BaseUrl = ConfigurationManager.AppSettings["RemedyEndPoint"];
        this.Url = BaseUrl + "&webService=" + "ATB_Springbooot_WS";
    }

    public AuthenticationInfo AuthenticationInfoValue
    {
        get
        {
            return this.authenticationInfoValueField;
        }
        set
        {
            this.authenticationInfoValueField = value;
        }
    }

    /// <remarks/>
    public event NotifyShipmentOrderConfirmationCompletedEventHandler NotifyShipmentOrderConfirmationCompleted;

    /// <remarks/>
    public event StatusUpdateCompletedEventHandler StatusUpdateCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ATB_Springbooot_WS/NotifyShipmentOrderConfirmation", 
        RequestNamespace = "urn:ATB_Springbooot_WS", ResponseNamespace = "urn:ATB_Springbooot_WS", 
        Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("Error_Code")]
    public string NotifyShipmentOrderConfirmation(string Order_ID, string Serial_Number, string SIM_ICCID, string SMSA_Tracking_Number, string TransactionNumber, out string Error_Message, out string Installation_Request_Number)
    {
        if (!string.IsNullOrEmpty(Serial_Number))
        {
            object[] results = this.Invoke("NotifyShipmentOrderConfirmation", new object[] {
                    Order_ID,
                    Serial_Number,
                    SIM_ICCID,
                    SMSA_Tracking_Number,
                    TransactionNumber});
            Error_Message = ((string)(results[1]));
            Installation_Request_Number = ((string)(results[2]));
            return ((string)(results[0]));
        }
        else
        {
            object[] results = this.Invoke("NotifyShipmentOrderConfirmation", new object[] {
                    Order_ID,
                     null,
                    SIM_ICCID,
                    SMSA_Tracking_Number,
                    TransactionNumber});
            Error_Message = ((string)(results[1]));
            Installation_Request_Number = ((string)(results[2]));
            return ((string)(results[0]));
        }
    }




    /// <remarks/>
    public System.IAsyncResult BeginNotifyShipmentOrderConfirmation(string Order_ID, string Serial_Number, string SIM_ICCID, string SMSA_Tracking_Number, string TransactionNumber, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("NotifyShipmentOrderConfirmation", new object[] {
                    Order_ID,
                    Serial_Number,
                    SIM_ICCID,
                    SMSA_Tracking_Number,
                    TransactionNumber}, callback, asyncState);
    }

    /// <remarks/>
    public string EndNotifyShipmentOrderConfirmation(System.IAsyncResult asyncResult, out string Error_Message, out string Installation_Request_Number)
    {
        object[] results = this.EndInvoke(asyncResult);
        Error_Message = ((string)(results[1]));
        Installation_Request_Number = ((string)(results[2]));
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void NotifyShipmentOrderConfirmationAsync(string Order_ID, string Serial_Number, string SIM_ICCID, string SMSA_Tracking_Number, string TransactionNumber)
    {
        this.NotifyShipmentOrderConfirmationAsync(Order_ID, Serial_Number, SIM_ICCID, SMSA_Tracking_Number, TransactionNumber, null);
    }

    /// <remarks/>
    public void NotifyShipmentOrderConfirmationAsync(string Order_ID, string Serial_Number, string SIM_ICCID, string SMSA_Tracking_Number, string TransactionNumber, object userState)
    {
        if ((this.NotifyShipmentOrderConfirmationOperationCompleted == null))
        {
            this.NotifyShipmentOrderConfirmationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyShipmentOrderConfirmationOperationCompleted);
        }
        this.InvokeAsync("NotifyShipmentOrderConfirmation", new object[] {
                    Order_ID,
                    Serial_Number,
                    SIM_ICCID,
                    SMSA_Tracking_Number,
                    TransactionNumber}, this.NotifyShipmentOrderConfirmationOperationCompleted, userState);
    }

    private void OnNotifyShipmentOrderConfirmationOperationCompleted(object arg)
    {
        if ((this.NotifyShipmentOrderConfirmationCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.NotifyShipmentOrderConfirmationCompleted(this, new NotifyShipmentOrderConfirmationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ATB_Springbooot_WS/StatusUpdate", RequestNamespace = "urn:ATB_Springbooot_WS", ResponseNamespace = "urn:ATB_Springbooot_WS", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("Installation_Request_Number")]
    public string StatusUpdate(string Order_ID, StatusType Status, [System.Xml.Serialization.XmlAttributeAttribute()] out string Error_Code, [System.Xml.Serialization.XmlAttributeAttribute()] out string Error_Message)
    {
        object[] results = this.Invoke("StatusUpdate", new object[] {
                    Order_ID,
                    Status});
        Error_Code = ((string)(results[1]));
        Error_Message = ((string)(results[2]));
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginStatusUpdate(string Order_ID, StatusType Status, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("StatusUpdate", new object[] {
                    Order_ID,
                    Status}, callback, asyncState);
    }

    /// <remarks/>
    public string EndStatusUpdate(System.IAsyncResult asyncResult, out string Error_Code, out string Error_Message)
    {
        object[] results = this.EndInvoke(asyncResult);
        Error_Code = ((string)(results[1]));
        Error_Message = ((string)(results[2]));
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void StatusUpdateAsync(string Order_ID, StatusType Status)
    {
        this.StatusUpdateAsync(Order_ID, Status, null);
    }

    /// <remarks/>
    public void StatusUpdateAsync(string Order_ID, StatusType Status, object userState)
    {
        if ((this.StatusUpdateOperationCompleted == null))
        {
            this.StatusUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatusUpdateOperationCompleted);
        }
        this.InvokeAsync("StatusUpdate", new object[] {
                    Order_ID,
                    Status}, this.StatusUpdateOperationCompleted, userState);
    }

    private void OnStatusUpdateOperationCompleted(object arg)
    {
        if ((this.StatusUpdateCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.StatusUpdateCompleted(this, new StatusUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ATB_Springbooot_WS")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ATB_Springbooot_WS", IsNullable = false)]
public partial class AuthenticationInfo : System.Web.Services.Protocols.SoapHeader
{

    private string userNameField;

    private string passwordField;

    private string authenticationField;

    private string localeField;

    private string timeZoneField;

    /// <remarks/>
    public string userName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }

    /// <remarks/>
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    public string authentication
    {
        get
        {
            return this.authenticationField;
        }
        set
        {
            this.authenticationField = value;
        }
    }

    /// <remarks/>
    public string locale
    {
        get
        {
            return this.localeField;
        }
        set
        {
            this.localeField = value;
        }
    }

    /// <remarks/>
    public string timeZone
    {
        get
        {
            return this.timeZoneField;
        }
        set
        {
            this.timeZoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ATB_Springbooot_WS")]
public enum StatusType
{

    /// <remarks/>
    New,

    /// <remarks/>
    Assigned,

    /// <remarks/>
    Scheduled,

    /// <remarks/>
    Transit,

    /// <remarks/>
    Completed,

    /// <remarks/>
    Pending,

    /// <remarks/>
    Failed,

    /// <remarks/>
    Cancelled,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void NotifyShipmentOrderConfirmationCompletedEventHandler(object sender, NotifyShipmentOrderConfirmationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class NotifyShipmentOrderConfirmationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal NotifyShipmentOrderConfirmationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }

    /// <remarks/>
    public string Error_Message
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }

    /// <remarks/>
    public string Installation_Request_Number
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[2]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void StatusUpdateCompletedEventHandler(object sender, StatusUpdateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StatusUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal StatusUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }

    /// <remarks/>
    public string Error_Code
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }

    /// <remarks/>
    public string Error_Message
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[2]));
        }
    }
}
