//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Go.SMSA.Services.EmailService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:stc:egate:jce:JavaException")]
    public partial class JavaExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string messageField;
        
        private string traceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eai.atheeb.net/emailNotification")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eai.atheeb.net/emailNotification")]
    public partial class EmailAck : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusField;
        
        private Error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eai.atheeb.net/emailNotification")]
    public partial class Attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attachmentContentField;
        
        private string attachmentContentTypeField;
        
        private string attachmentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attachmentContent {
            get {
                return this.attachmentContentField;
            }
            set {
                this.attachmentContentField = value;
                this.RaisePropertyChanged("attachmentContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string attachmentContentType {
            get {
                return this.attachmentContentTypeField;
            }
            set {
                this.attachmentContentTypeField = value;
                this.RaisePropertyChanged("attachmentContentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string attachmentName {
            get {
                return this.attachmentNameField;
            }
            set {
                this.attachmentNameField = value;
                this.RaisePropertyChanged("attachmentName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eai.atheeb.net/emailNotification")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageTextField;
        
        private string messageHTMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
                this.RaisePropertyChanged("messageText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageHTML {
            get {
                return this.messageHTMLField;
            }
            set {
                this.messageHTMLField = value;
                this.RaisePropertyChanged("messageHTML");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eai.atheeb.net/emailNotification")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mailIdField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mailId {
            get {
                return this.mailIdField;
            }
            set {
                this.mailIdField = value;
                this.RaisePropertyChanged("mailId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eai.atheeb.net/emailNotification")]
    public partial class SendMail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Address fromField;
        
        private Address[] toField;
        
        private Address[] ccField;
        
        private Address[] bccField;
        
        private Address[] replyToField;
        
        private string subjectField;
        
        private Message messageField;
        
        private Attachment[] attachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Address from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("to", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Address[] to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Address[] cc {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
                this.RaisePropertyChanged("cc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bcc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Address[] bcc {
            get {
                return this.bccField;
            }
            set {
                this.bccField = value;
                this.RaisePropertyChanged("bcc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("replyTo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Address[] replyTo {
            get {
                return this.replyToField;
            }
            set {
                this.replyToField = value;
                this.RaisePropertyChanged("replyTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Message message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Attachment[] attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("attachment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:stc:egate:jce:prjEmailNotification_otd_jcdEmailNotification", ConfigurationName="EmailService.ExecutePortType")]
    public interface ExecutePortType {
        
        // CODEGEN: Generating message contract since the operation oprEmailNotification is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:stc:egate:jce:prjEmailNotification_otd:jcdEmailNotificationWSDL:oprEmailNotif" +
            "ication", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Go.SMSA.Services.EmailService.JavaExceptionType), Action="urn:stc:egate:jce:prjEmailNotification_otd:jcdEmailNotificationWSDL:oprEmailNotif" +
            "ication", Name="JavaException", Namespace="urn:stc:egate:jce:JavaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Go.SMSA.Services.EmailService.Output oprEmailNotification(Go.SMSA.Services.EmailService.Input request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:stc:egate:jce:prjEmailNotification_otd:jcdEmailNotificationWSDL:oprEmailNotif" +
            "ication", ReplyAction="*")]
        System.Threading.Tasks.Task<Go.SMSA.Services.EmailService.Output> oprEmailNotificationAsync(Go.SMSA.Services.EmailService.Input request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Input {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eai.atheeb.net/emailNotification", Order=0)]
        public Go.SMSA.Services.EmailService.SendMail sendMail;
        
        public Input() {
        }
        
        public Input(Go.SMSA.Services.EmailService.SendMail sendMail) {
            this.sendMail = sendMail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Output {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eai.atheeb.net/emailNotification", Order=0)]
        public Go.SMSA.Services.EmailService.EmailAck EmailAck;
        
        public Output() {
        }
        
        public Output(Go.SMSA.Services.EmailService.EmailAck EmailAck) {
            this.EmailAck = EmailAck;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExecutePortTypeChannel : Go.SMSA.Services.EmailService.ExecutePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecutePortTypeClient : System.ServiceModel.ClientBase<Go.SMSA.Services.EmailService.ExecutePortType>, Go.SMSA.Services.EmailService.ExecutePortType {
        
        public ExecutePortTypeClient() {
        }
        
        public ExecutePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecutePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Go.SMSA.Services.EmailService.Output Go.SMSA.Services.EmailService.ExecutePortType.oprEmailNotification(Go.SMSA.Services.EmailService.Input request) {
            return base.Channel.oprEmailNotification(request);
        }
        
        public Go.SMSA.Services.EmailService.EmailAck oprEmailNotification(Go.SMSA.Services.EmailService.SendMail sendMail) {
            Go.SMSA.Services.EmailService.Input inValue = new Go.SMSA.Services.EmailService.Input();
            inValue.sendMail = sendMail;
            Go.SMSA.Services.EmailService.Output retVal = ((Go.SMSA.Services.EmailService.ExecutePortType)(this)).oprEmailNotification(inValue);
            return retVal.EmailAck;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Go.SMSA.Services.EmailService.Output> Go.SMSA.Services.EmailService.ExecutePortType.oprEmailNotificationAsync(Go.SMSA.Services.EmailService.Input request) {
            return base.Channel.oprEmailNotificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Go.SMSA.Services.EmailService.Output> oprEmailNotificationAsync(Go.SMSA.Services.EmailService.SendMail sendMail) {
            Go.SMSA.Services.EmailService.Input inValue = new Go.SMSA.Services.EmailService.Input();
            inValue.sendMail = sendMail;
            return ((Go.SMSA.Services.EmailService.ExecutePortType)(this)).oprEmailNotificationAsync(inValue);
        }
    }
}
